development: &default
  adapter: postgresql
  database: fuzzyblog_development
  pool: 5

test:
  <<: *default
  database: fuzzyblog_test

production:
  <<: *default
  database: fuzzyblog_production
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)
